In [2]:
import time
import re
import pandas as pd
from datetime import datetime as dt

column_names = ['EMPLOYEE_INFO_ID', 'REGION', 'DISTRICT', 'TEHSIL', 'UC_NAME',
       'INSTITUTION_CODE', 'INSTITUTION_PREFIX', 'INSTITUTION_NAME',
       'INSTITUTION_CATEGORY', 'EMPLOYEE_NAME', 'EMPLOYEE_FATHER_NAME',
       'EMPLOYEE_CNIC', 'EMPLOYEE_GENDER', 'DATE_OF_BIRTH', 'QUALIFICATION',
       'EMPLOYEE_PERSONNEL_ID', 'DESIGNATION', 'PAY_SCALE', 'DATE_OF_JOINING',
       'IS_RETIRED', 'RETIRED_DATE', 'JOB_CADRE']
for i in range(1, 50):
    url = "http://checker.sindheducation.gov.pk:78/WebApplication1/Home/GetPage/?token=ztiGer000&pid="+str(i)
    df = pd.read_json(url)
    df
    if(df.empty):
        print("Records doesn't exist")
        break
    else:
        try:    
            for index, row in df.iterrows(): 
                tsUtc = re.split('\(|\)', row['DATE_OF_BIRTH'])[1][:15]
                tsUtc = int(tsUtc)
                timestamp = tsUtc/1000
                print(timestamp)
                date = datetime.datetime(1970, 1, 1) + datetime.timedelta(seconds=(timestamp))
                new = pd.to_datetime(date).date() + pd.DateOffset(days=1)
                print("Epoch time: " , tsUtc, "Converted Time: ", new)
                df['DOB'] = new
    
                    #df.to_csv('D:/Emp_SELD.csv', mode = 'a', header = False) 
                print(df)
        except:
            print("Record Not Found")
#         with open('D:/Emp_SELD.csv', 'a') as f:
#             df.to_csv(f, header=f.tell()==0)    
# print("Completed")

-392360400.0
Record Not Found
-2696400.0
Record Not Found
-128926800.0
Record Not Found
131310000.0
Record Not Found

PermissionError: [Errno 13] Permission denied: 'D:/Emp_SELD.csv'

In [11]:
import time
import re
import pandas as pd
from datetime import datetime as dt
import datetime


dict = {}


url = "http://checker.sindheducation.gov.pk:78/WebApplication1/Home/GetPage/?token=ztiGer000&pid=1"
df = pd.read_json(url)
df

,EMPLOYEE_INFO_ID,REGION,DISTRICT,TEHSIL,UC_NAME,INSTITUTION_CODE,INSTITUTION_PREFIX,INSTITUTION_NAME,INSTITUTION_CATEGORY,EMPLOYEE_NAME,...,EMPLOYEE_GENDER,DATE_OF_BIRTH,QUALIFICATION,EMPLOYEE_PERSONNEL_ID,DESIGNATION,PAY_SCALE,DATE_OF_JOINING,IS_RETIRED,RETIRED_DATE,JOB_CADRE
0,1,Karachi,Karachi Central,Liaqatabad Town,45-Hadi Market,408150223,GGHS,ISHATUL QURAN,School,ZUBEDA SIBTAY,...,F,/Date(-392360400000)/,B.A,10065230,H.M,17,/Date(465418800000)/,1,/Date(1501009200000)/,Non-Teaching
1,2,Shaheed Benazirabad,Shaheed Benazirabad,Nawab Shah,-,701020673,DEO,DEO OFFICE PRIMARY SHAHEED BENAZIRABAD,School,SHAZIA VISTRO,...,F,/Date(744490800000)/,None,10746774,NAIB QASID,2,/Date(1339182000000)/,0,None,Non-Teaching
2,3,Karachi,Karachi Central,Karachi Central,-,702921980,DEO,DEO LITERACY DISTRICT KARACHI CENTRAL,School,MAQSOOD ALI RAJPER,...,M,/Date(272746800000)/,B.A,10746764,OFFICE ASSISTANT,14,/Date(1337108400000)/,0,None,Non-Teaching
3,4,Karachi,Karachi East,Jamshed Town,14-Fatima Jinnah,408070099,GGPS,G.G.P.S. B.Y.J.URDU,School,SHAHEEN MUHAMMAD SADIQ,...,M,/Date(-72075600000)/,None,10078945,PST,9,/Date(652820400000)/,1,None,Teaching
4,11,Karachi,Karachi Central,New Karachi Town,07-Faisal,408130215,GGHS,5 NEW KARACHI,School,NASREEN FATIMA,...,F,/Date(-378968400000)/,M.A,10055364,HST,16,/Date(504644400000)/,1,None,Teaching
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6711,9996,Shaheed Benazirabad,Shaheed Benazirabad,Daur,Daur Town-Tc,417040221,GBPS,MODEL COLONY DAUR,School,JAVED AHMED JAMALI,...,M,/Date(638132400000)/,B.A,10678140,PST,9,/Date(1271790000000)/,0,None,Teaching
6712,9997,Shaheed Benazirabad,Shaheed Benazirabad,Sakrand,4- Kumb Leema,917000030,GBPS,HAJI IMAM DIN BROHI,School,AMIR AHMED,...,M,/Date(-178952400000)/,M.A,10212668,PST,9,/Date(656535600000)/,9,None,Teaching
6713,9998,Shaheed Benazirabad,Shaheed Benazirabad,Daur,Khan Muhammad Khan Jalbani,417040493,GBPS,CHUDHRY INAYAT ALI,School,MUHAMMAD SALEEM MIRANI,...,M,/Date(265748400000)/,B.A,10675946,PST,9,/Date(1283540400000)/,0,None,Teaching
6714,9999,Shaheed Benazirabad,Shaheed Benazirabad,Daur,Daur Town-Tc,417040048,GBPS,RAZA ABAD,School,ISIM MUHAMMAD,...,M,/Date(-153464400000)/,B.A,10216854,PST,9,/Date(698958000000)/,0,None,Teaching
6715,10000,Shaheed Benazirabad,Shaheed Benazirabad,Daur,Daur Town-Tc,417040102,GBPS,MAIN SINDHI DAUR,School,MUHAMMAD MOUSA,...,M,/Date(-23778000000)/,B.A,10216706,PST,9,/Date(612471600000)/,0,None,Teaching

In [12]:
# df['RETIRED_DATE'] = pd.to_datetime(df['RETIRED_DATE'])
# df

In [18]:
import time
import re
import pandas as pd
import csv
from csv import DictWriter

column_names = ['EMPLOYEE_INFO_ID', 'REGION', 'DISTRICT', 'TEHSIL', 'UC_NAME',
       'INSTITUTION_CODE', 'INSTITUTION_PREFIX', 'INSTITUTION_NAME',
       'INSTITUTION_CATEGORY', 'EMPLOYEE_NAME', 'EMPLOYEE_FATHER_NAME',
       'EMPLOYEE_CNIC', 'EMPLOYEE_GENDER', 'DATE_OF_BIRTH', 'QUALIFICATION',
       'EMPLOYEE_PERSONNEL_ID', 'DESIGNATION', 'PAY_SCALE', 'DATE_OF_JOINING',
       'IS_RETIRED', 'RETIRED_DATE', 'JOB_CADRE']


for i in range(1, 50):
    try: 
        url = "http://checker.sindheducation.gov.pk:78/WebApplication1/Home/GetPage/?token=ztiGer000&pid="+str(i)
        df = pd.read_json(url)
        df
        if(df.empty):
            print("Records doesn't exist")
            break
        else:
            for index, row in df.iterrows(): 
                emp_info_id = row['EMPLOYEE_INFO_ID']
                dict[column_names[0]] = row['EMPLOYEE_INFO_ID']

                region = row['REGION']
                dict[column_names[1]] = row['REGION']

                district = row['DISTRICT']
                dict[column_names[2]] = row['DISTRICT']

                tehsil = row['TEHSIL']
                dict[column_names[3]] = row['TEHSIL']

                ucName = row['UC_NAME']
                dict[column_names[4]] = row['UC_NAME']

                inst_code = row['INSTITUTION_CODE']
                dict[column_names[5]] = row['INSTITUTION_CODE']

                inst_pre = row['INSTITUTION_PREFIX']
                dict[column_names[6]] = row['INSTITUTION_PREFIX']

                inst_name = row['INSTITUTION_NAME']
                dict[column_names[7]] = row['INSTITUTION_NAME']

                inst_cat = row['INSTITUTION_CATEGORY']
                dict[column_names[8]] = row['INSTITUTION_CATEGORY']

                emp_name = row['EMPLOYEE_NAME']
                dict[column_names[9]] = row['EMPLOYEE_NAME']

                emp_father_name = row['EMPLOYEE_FATHER_NAME']
                dict[column_names[10]] = row['EMPLOYEE_FATHER_NAME']

                emp_cnic = row['EMPLOYEE_CNIC']
                dict[column_names[11]] = row['EMPLOYEE_CNIC']

                emp_gender = row['EMPLOYEE_GENDER']
                dict[column_names[12]] = row['EMPLOYEE_GENDER']

                try:

                    dob_ep = re.split('\(|\)', str(row['DATE_OF_BIRTH']))[1][:15]
                    dob_ep = int(dob_ep)
                    date_ep = datetime.datetime(1970, 1, 1) + datetime.timedelta(seconds=(dob_ep/1000))
                    dob = pd.to_datetime(date_ep).date() + pd.DateOffset(days=1)

                    d_o_b = dob
                    dict[column_names[13]] = dob
                except:
                    dict[column_names[13]] = ""

                qualification = row['QUALIFICATION']
                dict[column_names[14]] = row['QUALIFICATION']

                emp_per_id = row['EMPLOYEE_PERSONNEL_ID']
                dict[column_names[15]] = row['EMPLOYEE_PERSONNEL_ID']

                designation = row['DESIGNATION']
                dict[column_names[16]] = row['DESIGNATION']

                pay_scale = row['PAY_SCALE']
                dict[column_names[17]] = row['PAY_SCALE']

                try:

                    doj_ep = re.split('\(|\)', str(row['DATE_OF_JOINING']))[1][:15]
                    doj_ep = int(doj_ep)
                    date_j = datetime.datetime(1970, 1, 1) + datetime.timedelta(seconds=(doj_ep/1000))
                    doj = pd.to_datetime(date_j, format='%yyyy-%mm-%dd').date() + pd.DateOffset(days=1)

                    date_of_joining = doj
                    dict[column_names[18]] = doj
                except:
                    dict[column_names[18]] = ""

                is_retired = row['IS_RETIRED']
                dict[column_names[19]] = row['IS_RETIRED']

                #dates_r = row['RETIRED_DATE'].applymap(lambda x: "{0}/{1}/{2} {3}:{4}:{5}".format(x[0],x[1],x[2], x[3], x[4], x[5]) if len(x)==15 else '')
                #dct = {k: None if not v else v for k, v in dct.items() } 

                try:
                    dor_ep = re.split('\(|\)', str(row['RETIRED_DATE']))[1][:25]
                    dor_ep = int(dor_ep)
                    date_r = datetime.datetime(1970, 1, 1) + datetime.timedelta(seconds=(dor_ep/1000))
                    dor = pd.to_datetime(date_r).date() + pd.DateOffset(days=1)
                    d_o_r = dor
                    dict[column_names[20]] = dor        
                except:
                    dict[column_names[20]] = ""

                job_cadre = row['JOB_CADRE']
                dict[column_names[21]] = row['JOB_CADRE']


                with open(r'D:/RecordsEmp_SELD.csv', 'a', newline='') as f_object:
                    dictwriter_object = csv.DictWriter(f_object, fieldnames=column_names)            
                    if index == 0:
                        dictwriter_object.writeheader()      
                    dictwriter_object.writerow(dict)
                    dict.clear()
            print("RecordSet ",i," Inserted")    
    except:
        print("Completed")
        break

RecordSet  1  Inserted
RecordSet  2  Inserted
RecordSet  3  Inserted
RecordSet  4  Inserted
RecordSet  5  Inserted
RecordSet  6  Inserted
RecordSet  7  Inserted
RecordSet  8  Inserted
RecordSet  9  Inserted
RecordSet  10  Inserted
RecordSet  11  Inserted
RecordSet  12  Inserted
RecordSet  13  Inserted
RecordSet  14  Inserted
RecordSet  15  Inserted
RecordSet  16  Inserted
RecordSet  17  Inserted
RecordSet  18  Inserted
RecordSet  19  Inserted
RecordSet  20  Inserted
RecordSet  21  Inserted
RecordSet  22  Inserted
RecordSet  23  Inserted
RecordSet  24  Inserted

ValueError: Expected object or value

In [ ]:


        
        
        
        #         row['DATE_OF_BIRTH'] = dob
#         print("Epoch time: " , dob_ep, "Converted Time: ", dob)
        
#         print(df)
# #         with open('D:/Emp_test.csv', 'a') as f:
#             df.to_csv(f, header=f.tell()==0)  
#     df['DATE_OF_BIRTH'] = dob
#     df
    
#     print(time.strftime('%d-%m-%Y', time.gmtime(tsUtc/1000)))