In [1]:
import pandas as pd

In [3]:
file = pd.read_spss("E:/PDHS/PDHS 2017-18/2017-18/2017-18/SPSS/PK_2017-18_DHS_02252019_1144_45473/PKBR71SV/PKBR71FL.SAV")
phds_17 = pd.DataFrame(file)

In [4]:
phds_17

,CASEID,BIDX,V000,V001,V002,V003,V004,V005,V006,V007,...,SD005,IDX94,S409A,S413AA,S413AB,S413AC,S437A,S443A,S451A,S469A
0,1 1 2,1.0,PK7,1.0,1.0,2.0,1.0,868683.0,2.0,2018.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Child has grown
1,1 1 2,2.0,PK7,1.0,1.0,2.0,1.0,868683.0,2.0,2018.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1 1 2,3.0,PK7,1.0,1.0,2.0,1.0,868683.0,2.0,2018.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1 1 2,4.0,PK7,1.0,1.0,2.0,1.0,868683.0,2.0,2018.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1 1 2,5.0,PK7,1.0,1.0,2.0,1.0,868683.0,2.0,2018.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50490,580 26 2,3.0,PK7,580.0,26.0,2.0,580.0,0.0,2.0,2018.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50491,580 28 3,1.0,PK7,580.0,28.0,3.0,580.0,0.0,2.0,2018.0,...,NaN,1.0,Yes,No,No,Yes,No,Yes,NaN,Child has grown
50492,580 28 3,2.0,PK7,580.0,28.0,3.0,580.0,0.0,2.0,2018.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50493,580 28 3,3.0,PK7,580.0,28.0,3.0,580.0,0.0,2.0,2018.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50494,580 28 3,4.0,PK7,580.0,28.0,3.0,580.0,0.0,2.0,2018.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
phds_17.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50495 entries, 0 to 50494
Columns: 1186 entries, CASEID to S469A
dtypes: category(1087), float64(97), object(2)
memory usage: 93.9+ MB

In [6]:
phds_17.describe()

,BIDX,V001,V002,V003,V004,V005,V006,V007,V008,V008A,...,HW18,HW19,IDXML,SWFEDUC1,SWFREGUR,S207BB,S908C,SV005,SD005,IDX94
count,50495.000000,50495.000000,50495.000000,50495.000000,50495.000000,5.049500e+04,50495.000000,50495.000000,50495.000000,50495.000000,...,4499.000000,4499.000000,12708.000000,50495.000000,50495.000000,50495.000000,8514.000000,5.049500e+04,1.458800e+04,12708.000000
mean,3.101733,283.896802,14.276819,2.969244,283.896802,8.086081e+05,4.808555,2017.702565,1417.239331,43122.697317,...,4.763725,2017.708380,1.411001,114.212417,91.234895,0.582513,3.441156,1.904467e+05,1.852701e+05,1.411001
std,2.054793,165.248141,8.083951,2.741223,165.248141,8.963839e+05,4.667234,0.457134,1.130393,33.267087,...,4.643681,0.454559,0.614631,80.040449,68.937944,1.000396,5.091723,5.732144e+05,5.728225e+05,0.614631
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000e+00,1.000000,2017.000000,1415.000000,43044.000000,...,1.000000,2017.000000,1.000000,100.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,1.000000
25%,1.000000,141.000000,7.000000,2.000000,141.000000,7.027000e+04,1.000000,2017.000000,1416.000000,43096.000000,...,1.000000,2017.000000,1.000000,103.000000,100.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,1.000000
50%,3.000000,279.000000,14.000000,2.000000,279.000000,4.306380e+05,2.000000,2018.000000,1417.000000,43122.000000,...,2.000000,2018.000000,1.000000,105.000000,103.000000,0.000000,1.000000,0.000000e+00,0.000000e+00,1.000000
75%,4.000000,414.000000,21.000000,3.000000,414.000000,1.280550e+06,12.000000,2018.000000,1418.000000,43149.000000,...,12.000000,2018.000000,2.000000,111.000000,110.000000,1.000000,5.000000,0.000000e+00,0.000000e+00,2.000000
max,15.000000,580.000000,29.000000,40.000000,580.000000,4.095189e+06,12.000000,2018.000000,1420.000000,43218.000000,...,12.000000,2018.000000,5.000000,7760.000000,3009.000000,20.000000,30.000000,6.130408e+06,9.866741e+06,5.000000